// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ-0mwKjYW6cIkBYsNEFHTJ2FDZAJj1N8',
    appId: '1:509898618459:web:f5ad8a7daed246715a317e',
    messagingSenderId: '509898618459',
    projectId: 'website-sombo',
    authDomain: 'website-sombo.firebaseapp.com',
    storageBucket: 'website-sombo.firebasestorage.app',
    measurementId: 'G-DLMK20THTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ-0mwKjYW6cIkBYsNEFHTJ2FDZAJj1N8',
    appId: '1:509898618459:android:YOUR_ANDROID_ID',
    messagingSenderId: '509898618459',
    projectId: 'website-sombo',
    storageBucket: 'website-sombo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ-0mwKjYW6cIkBYsNEFHTJ2FDZAJj1N8',
    appId: '1:509898618459:ios:YOUR_IOS_ID',
    messagingSenderId: '509898618459',
    projectId: 'website-sombo',
    storageBucket: 'website-sombo.firebasestorage.app',
    iosBundleId: 'com.example.elearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ-0mwKjYW6cIkBYsNEFHTJ2FDZAJj1N8',
    appId: '1:509898618459:ios:YOUR_MACOS_ID',
    messagingSenderId: '509898618459',
    projectId: 'website-sombo',
    storageBucket: 'website-sombo.firebasestorage.app',
    iosBundleId: 'com.example.elearning',
  );
}
